import { Vehicle } from "@/types";

export const SAMPLE_FLEET: Vehicle[] = [
  {
    id: "veh-001",
    brand: "Porsche",
    model: "911 GT3 RS",
    year: 2024,
    license_plate: "LUX-911",
    category: "sports",
    transmission: "automatic",
    fuel_type: "petrol",
    seats: 2,
    doors: 2,
    mileage: 3200,
    color: "Shark Blue",
    status: "available",
    daily_rate: "890.00",
    weekly_rate: "5400.00",
    monthly_rate: "19500.00",
    deposit_amount: "2500.00",
    features: [
      "4.0L Naturally Aspirated Boxer-6",
      "PDK 7-Speed Dual-Clutch",
      "Carbon Ceramic Brakes (PCCB)",
      "Club Sport Package",
      "Front Axle Lift System",
    ],
    images: [
      {
        url: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
      },
    ],
    description: "The benchmark high-revving road-legal racecar. 518 hp, active aerodynamics, and peerless precision.",
    branch_id: "branch-01",
  },
  {
    id: "veh-002",
    brand: "Land Rover",
    model: "Range Rover SV Autobiography",
    year: 2024,
    license_plate: "SV-440",
    category: "luxury",
    transmission: "automatic",
    fuel_type: "hybrid",
    seats: 5,
    doors: 4,
    mileage: 6400,
    color: "Belgravia Green",
    status: "available",
    daily_rate: "750.00",
    weekly_rate: "4600.00",
    monthly_rate: "16800.00",
    deposit_amount: "2000.00",
    features: [
      "Executive Rear Seating with Massage",
      "Meridian Signature 1600W Sound",
      "Adaptive Off-Road Air Suspension",
      "Acoustic Laminated Glass",
      "Chilled Rear Armrest Refrigerator",
    ],
    images: [
      {
        url: "https://images.unsplash.com/photo-1541348263662-e0c8de4259ba?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
      },
    ],
    description: "The quintessential luxury flagship SUV. Serene cabin refinement with peerless all-terrain mastery.",
    branch_id: "branch-01",
  },
  {
    id: "veh-003",
    brand: "Tesla",
    model: "Model S Plaid",
    year: 2024,
    license_plate: "EV-1020",
    category: "electric",
    transmission: "automatic",
    fuel_type: "electric",
    seats: 5,
    doors: 4,
    mileage: 5100,
    color: "Solid Black",
    status: "available",
    daily_rate: "490.00",
    weekly_rate: "3100.00",
    monthly_rate: "11200.00",
    deposit_amount: "1500.00",
    features: [
      "Tri-Motor All-Wheel Drive (1,020 HP)",
      "0-60 mph in 1.99s",
      "Full Self-Driving Capability Supervised",
      "Free Supercharging Included",
      "Yoke Steering with Gaming Computer",
    ],
    images: [
      {
        url: "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
      },
    ],
    description: "The fastest accelerating production sedan on earth. Instant torque, zero emissions, and cutting-edge tech.",
    branch_id: "branch-01",
  },
  {
    id: "veh-004",
    brand: "Mercedes-AMG",
    model: "G 63 Biturbo",
    year: 2024,
    license_plate: "AMG-630",
    category: "suv",
    transmission: "automatic",
    fuel_type: "petrol",
    seats: 5,
    doors: 5,
    mileage: 8200,
    color: "Designo Night Black Magno",
    status: "available",
    daily_rate: "950.00",
    weekly_rate: "5900.00",
    monthly_rate: "21000.00",
    deposit_amount: "3000.00",
    features: [
      "4.0L Handcrafted V8 Biturbo (577 HP)",
      "AMG Side-Exit Exhaust System",
      "Triple Locking Differentials",
      "Burmester Surround Sound",
      "22-inch Forged Monoblock Wheels",
    ],
    images: [
      {
        url: "https://images.unsplash.com/photo-1520031441872-265e4ff70366?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
      },
    ],
    description: "Unrivaled presence and brutal performance. Handcrafted AMG V8 sound wrapped in an iconic boxy silhouette.",
    branch_id: "branch-01",
  },
  {
    id: "veh-005",
    brand: "BMW",
    model: "i7 xDrive60 Excellence",
    year: 2024,
    license_plate: "VIP-007",
    category: "luxury",
    transmission: "automatic",
    fuel_type: "electric",
    seats: 5,
    doors: 4,
    mileage: 4300,
    color: "Oxide Grey Metallic",
    status: "available",
    daily_rate: "680.00",
    weekly_rate: "4200.00",
    monthly_rate: "15500.00",
    deposit_amount: "1800.00",
    features: [
      "31.3-inch 8K Theatre Screen in Rear",
      "Bowers & Wilkins Diamond 4D Sound",
      "Automatic Power Doors",
      "Crystal Headlights by Swarovski",
      "Executive Lounge Seating",
    ],
    images: [
      {
        url: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
      },
    ],
    description: "The pinnacle of electric executive travel. Private cinema rear lounge with whisper-quiet electric drive.",
    branch_id: "branch-01",
  },
  {
    id: "veh-006",
    brand: "Land Rover",
    model: "Defender 110 Trophy Edition",
    year: 2024,
    license_plate: "EXP-110",
    category: "suv",
    transmission: "automatic",
    fuel_type: "diesel",
    seats: 5,
    doors: 5,
    mileage: 11200,
    color: "Gondwana Stone",
    status: "available",
    daily_rate: "420.00",
    weekly_rate: "2600.00",
    monthly_rate: "9400.00",
    deposit_amount: "1200.00",
    features: [
      "Integrated Expedition Roof Rack & Ladder",
      "WARN Electric Winch & Recovery Kit",
      "Raised Air Intake (Snorkel)",
      "ClearSight Ground View Camera",
      "All-Terrain Tires with 291mm Clearance",
    ],
    images: [
      {
        url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
      },
    ],
    description: "The ultimate adventure expedition machine. Engineered to conquer harsh mountain terrain with total confidence.",
    branch_id: "branch-01",
  },
  {
    id: "veh-007",
    brand: "Polestar",
    model: "Polestar 2 Long Range Dual Motor",
    year: 2024,
    license_plate: "PS-240",
    category: "compact",
    transmission: "automatic",
    fuel_type: "electric",
    seats: 5,
    doors: 5,
    mileage: 7800,
    color: "Midnight Blue",
    status: "available",
    daily_rate: "240.00",
    weekly_rate: "1500.00",
    monthly_rate: "5400.00",
    deposit_amount: "800.00",
    features: [
      "Öhlins Dual Flow Valve Dampers",
      "Brembo 4-Piston Gold Brakes",
      "Google Built-in Android Automotive",
      "Harman Kardon Premium Audio",
      "Eco-Weave Vegan Interior",
    ],
    images: [
      {
        url: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
      },
    ],
    description: "Scandinavia's sharpest electric fastback. Compact agility, clean aesthetics, and instant city speed.",
    branch_id: "branch-01",
  },
  {
    id: "veh-008",
    brand: "Audi",
    model: "RS 6 Avant Performance",
    year: 2024,
    license_plate: "RS-630",
    category: "sports",
    transmission: "automatic",
    fuel_type: "petrol",
    seats: 5,
    doors: 5,
    mileage: 6100,
    color: "Nardo Grey",
    status: "reserved",
    daily_rate: "720.00",
    weekly_rate: "4400.00",
    monthly_rate: "16200.00",
    deposit_amount: "2000.00",
    features: [
      "4.0L Twin-Turbo V8 (621 HP)",
      "Quattro Sport Differential",
      "Dynamic All-Wheel Steering",
      "RS Sport Exhaust with Black Oval Tips",
      "Bang & Olufsen 3D Advanced Sound",
    ],
    images: [
      {
        url: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80",
        is_primary: true,
      },
    ],
    description: "The supercar disguised as an estate. Blistering cross-country pace with practical luggage volume.",
    branch_id: "branch-01",
  },
];
